### PR TITLE
feat: nixpkgs-ify and unflake-ify system-manager

### PR DESCRIPTION
**Pull request by soupglasses**
Make it easier to use system-manager as a flake-library.

Will remove from all dependents at least 230 lines worth of locks from this project ([Example](https://github.com/soupglasses/nix-system-graphics/commit/50b028cfbe4c0f9173809ea13eb01e470676bd90)), while still keeping the same library.

Further adds flexibility to calling the libraries and package adding the possibility to use `default.nix` or invoking the files directly. ([Example](https://github.com/soupglasses/nix-system-graphics/blob/f4af5be53039c5e456899f8d911dfe41207151e3/flake.nix#L32-L41))

Note differences in calling `lib.nix` directly, the removal of the flake layout of `default.nix` being a breaking change, and most importantly the `packages.nix` only having a single wrapped binary output called `system-manager` instead of the four previous ones. Open to change anything here (like adding back packages).

Thanks for this project! :tada:

### CODE REVIEW

**Comment by soupglasses** [comment]
Note, using system-manager outside of a `flake.nix` is entirely untested currently.

**Comment by soupglasses** [comment]
Realize i removed treefmt, which could be added back.

**Comment by soupglasses** [comment]
Added back treefmt support :+1:

**Comment by soupglasses** [comment]
TODO: Should add in aliases for the removed packages? Possibly re-add them? Unsure if they are meant to be used outside of `system-manager`'s development cycle.

**Comment by soupglasses** [comment]
Seems #136 got squashed into [feat: add overlay](https://github.com/numtide/system-manager/pull/125/commits/c87df5fe91a4d4d1e74a183de7873c35365fd70e), not what i intended but its there.

**Comment by soupglasses** [comment]
Fixed the incorrect squash :+1:

**Comment by soupglasses** [comment]
Tried to find a better way to expose the nix-vm-test project, but i cannot really find a good way to let it auto update but also not propagate as a dev dependency to all users of system-manager.

We could eye out moving all the nix libraries in here to a `system-manager-modules` as well as making a PR to nixpkgs to add a `system-manager` based upon the work here. Then it would become a lot simpler to use system-manager, and there wouldn't be a need to simply the developer nix flake here. Only add a new input for `inputs.system-manager-modules` for the modules.

But it is annoying to have to split it up like this however.

**Review by zimbatm — APPROVED** [review]
very nice, thank you @soupglasses

**Comment by zimbatm** [comment]
Another way is to create a ./dev flake, we do this in a couple of projects. It allows hiding the dev dependencies from the user's flake.lock. You can find an example of it in https://github.com/nix-community/srvos. This would make the management of the nix-vm-test input easier.

But this is good enough to be merged already.

**Pull request merged**
